// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://toitgmaeuscrdwbpntda.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaXRnbWFldXNjcmR3YnBudGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMjMzOTksImV4cCI6MjA4Njc5OTM5OX0.HmWokm-8GjME-2tBoE9JXyvaIoJwiOJlsdiDkp6Qa6M';

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const envSupabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const requireSupabaseEnv = import.meta.env.VITE_REQUIRE_SUPABASE_ENV === "true";
const isDevMode = import.meta.env.DEV;

const hasEnvConfig = Boolean(envSupabaseUrl && envSupabasePublishableKey);

if (!hasEnvConfig) {
  if (requireSupabaseEnv) {
    throw new Error(
      "VITE_REQUIRE_SUPABASE_ENV is set but VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is missing. Copy .env.example to .env or set the vars."
    );
  }
  if (isDevMode) {
    console.warn(
      "VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY not set. Using default project. Copy .env.example to .env to silence."
    );
  }
}

export const SUPABASE_URL = envSupabaseUrl ?? DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = envSupabasePublishableKey ?? DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
