// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://dxvbmvbzobcjhzozuqkb.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dmJtdmJ6b2Jjamh6b3p1cWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1OTE1NDcsImV4cCI6MjA4NzE2NzU0N30.wG2DcAC0Cdrp2K1vyzS2Fl5waPsv47g3qmVbA118qQo';

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const envSupabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const requireSupabaseEnv = import.meta.env.VITE_REQUIRE_SUPABASE_ENV === "true";

if (requireSupabaseEnv && (!envSupabaseUrl || !envSupabasePublishableKey)) {
  throw new Error(
    "Missing Supabase environment configuration while VITE_REQUIRE_SUPABASE_ENV=true. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
  );
}

if (!envSupabaseUrl || !envSupabasePublishableKey) {
  console.warn(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Falling back to default project credentials."
  );
}

const SUPABASE_URL = envSupabaseUrl ?? DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = envSupabasePublishableKey ?? DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});