// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://toitgmaeuscrdwbpntda.supabase.co';
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaXRnbWFldXNjcmR3YnBudGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMjMzOTksImV4cCI6MjA4Njc5OTM5OX0.HmWokm-8GjME-2tBoE9JXyvaIoJwiOJlsdiDkp6Qa6M';

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const envSupabasePublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const fallbackAllowed = import.meta.env.VITE_ALLOW_SUPABASE_FALLBACK === "true";
const requireSupabaseEnv = import.meta.env.VITE_REQUIRE_SUPABASE_ENV === "true";
const isDevMode = import.meta.env.DEV;

const hasEnvConfig = Boolean(envSupabaseUrl && envSupabasePublishableKey);

if (!hasEnvConfig) {
  const errorMessage =
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. This can point the app to the wrong Supabase project and cause schema/policy mismatches.";

  if (requireSupabaseEnv || (!isDevMode && !fallbackAllowed)) {
    throw new Error(
      `${errorMessage} Set the missing env vars (recommended), or explicitly allow fallback with VITE_ALLOW_SUPABASE_FALLBACK="true" in local/dev-only contexts.`
    );
  }

  if (fallbackAllowed) {
    console.warn(
      `${errorMessage} Falling back to default project credentials because VITE_ALLOW_SUPABASE_FALLBACK="true".`
    );
  }
}

export const SUPABASE_URL = envSupabaseUrl ?? DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = envSupabasePublishableKey ?? DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
